export default {
  GET_TEMPLATE_LIST: 'GET_TEMPLATE_LIST',

  GET_TEMPLATE_DETAILS: 'GET_TEMPLATE_DETAILS',

  UPDATE_TEMPLATE: 'UPDATE_TEMPLATE',

  CLEAR_TEMPLATE_DETAILS: 'CLEAR_TEMPLATE_DETAILS',
};
